language: python
python: 3.4

install:
    - pip install -r requirements.txt
    - pip freeze
script:
     - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pylint $TRAVIS_BUILD_DIR/py3.py; python $TRAVIS_BUILD_DIR/py3.py;  fi
     - /usr/bin/python $TRAVIS_BUILD_DIR/py27.py
