notifications:
  email: false

language: python
python: 3.4

install:
#    - travis_retry pip install -r requirements.txt
    - travis_retry pip install pylint
    - pip freeze

script:
     - python $TRAVIS_BUILD_DIR/py3.py
     - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pylint $TRAVIS_BUILD_DIR/py3.py;  fi
     - /usr/bin/python $TRAVIS_BUILD_DIR/py27.py
